### ISSUE TITLE
是否支持集群模式？

### ISSUE THREAD

**Issue by yangkebiao** [majianzheng/jarboot#19]
比如多台服务器，多实例的管理

**Comment by majianzheng** [comment]
目前的功能定位是像Arthas这样的基础工具，多服务器多节点的管理有`k8s`这类工具，jarboot目前是作为某一节点下的启动管理工具。集群可视化管理可以作为下一阶段的开发需求，取代现有的成熟工具难度很大。

**Comment by majianzheng** [comment]
已经支持以客户端模式与k8s、Docker进行无侵入式的集成
