### ISSUE TITLE
设置-D属性启动不了项目

### ISSUE THREAD

**Issue by hello-AY** [majianzheng/jarboot#20]
正常命令   java  -Djava.ext.dirs=.\lib -Djava.security.egd=file:./urandom -Duser.timezone=GMT+08 -jar pro.jar 
用jarboot后生成的命令 -jar 在前，-D在后 ， 服务不能启动

**Comment by majianzheng** [comment]
# VM options配置目前是紧跟java后面的，如下图
![1](https://user-images.githubusercontent.com/50468276/129361801-55dc2e2e-1d58-4225-8d72-dd28cbb71bfe.png)

# Program arguments配置是程序传入参数，会放到最后面，你看下是不是配置错位置了

![2](https://user-images.githubusercontent.com/50468276/129362125-4b8bf4f2-c086-4b2c-8e87-0a20087d0a68.png)

**Comment by hello-AY** [comment]
好用了，是写在boot.vmoptions文件里，我是把参数写在VM那行输入框里了。
在问下，我输出到日志文件的内容，能显示到启动控制台吗

**Comment by majianzheng** [comment]
像目前常用的日志框架slf4j系列：logback、log4j是可以的，除非是配置里特意关掉了，本质上执行了`System.out`的方法都会显示，SpringBoot默认是`logback`也是目前性能最好的日志框架。
