### ISSUE TITLE
jarboot用nginx发布后，首页加载js和css错误无法打开页面

### ISSUE THREAD

**Issue by zhengeili** [majianzheng/jarboot#29]
jarboot用nginx发布后，首页加载js和css错误无法打开页面。nginx反向代理发布，比如带个后缀 localhost:8080/jarboot这种发布的形式。

**Comment by majianzheng** [comment]
前端未开放【/jarboot/】开头的路由，目前已经增加了该路由（#79b5d9d），过几天会发布新版本，急用的话可以先编译前端再编译后端。
访问地址为：http://loalhost:9899/jarboot/index.html，原访问地址也支持。
使用Nginx也可以支持动静分离，前端资源也可以使用Nginx代理，前端路由以【/jarboot/】开头，后端接口以【/api/jarboot/】开头

**Comment by zhengeili** [comment]
正在尝试用于生产环境，感谢，坐等新版本。

**Comment by majianzheng** [comment]
新版本已发布，注意不要忘了代理Websocket，websocket代理以/jarboot/开头，后端接口以/api/jarboot开头
@zhengeili
