### ISSUE TITLE
跟arthas有啥区别

### ISSUE THREAD

**Issue by zhengkaifor** [majianzheng/jarboot#32]

**Comment by majianzheng** [comment]
1、比Arthas的侵入性更小，Arthas会在宿主进程中开启Telnet服务和Web Server服务，占用宿主服务的进程资源，Jarboot则是将宿主进程以客户端的形式反向连接到诊断服务，占用更少；
2、诊断功能只是Jarboot的其中一部分功能，主要的功能是进程的启停、守护、监控等管理。

源码、技术架构对比：见博客[Arthas与Jarboot的源码实现对比](https://my.oschina.net/oldapple/blog/5118457)

@zhengkaifor
