### ISSUE TITLE
jarboot-ui中的console组件清屏并不会回收dom元素，造成内存泄漏

### ISSUE THREAD

**Issue by 2628356686** [majianzheng/jarboot#39]
原代码：
private handleClear() {
        if (this.isStartLoading) {
            //如果处于加载中，则保留加载的动画
            this.codeDom.innerHTML = "";
            this.codeDom.append(this.loading);
        } else {
            this.codeDom.innerHTML = "";
        }
    }
jarboot-ui前端项目中的console组件中使用innerHTML=“”的方式不会回收内存，使用 React.createRef() 创建的 DOM 元素的引用，会在组件卸载时被自动销毁，但是该 DOM 元素上添加的子元素，不会自动被销毁，因为它们不是 React 组件的一部分，而是原生 DOM 元素。
使用 innerHTML 清空该 DOM 元素的内容时，子元素并没有被销毁，而是仍然存在于内存中，会导致内存泄漏。建议使用遍历删除子孙元素的方式。
建议代码：
private handleClear() {
        if (this.isStartLoading) {
            //如果处于加载中，则保留加载的动画
            // this.codeDom.innerHTML = "";
            this.handleClick()    // 清屏逻辑更新使用循环递归删除子其子孙元素
            this.codeDom.append(this.loading);
        } else {
            // this.codeDom.innerHTML = "";
            this.handleClick()
        }
    }

    private handleClick = (): void => {
        const wrapper = this.codeDom;
        if (wrapper) {
        while (wrapper.firstChild) {
            wrapper.removeChild(wrapper.firstChild);
        }
        }
    };
    private removeChildNodes = (node: Node): void => {
        while (node.firstChild) {
        this.removeChildNodes(node.firstChild);
        node.removeChild(node.firstChild);
        }
    };

**Comment by majianzheng** [comment]
已使用vue3重构，使用xterm实现
